```{r}
bayesTheorem <- function(pA, pB, pBA)
  pAB <- (pA * pBA)/pB
```


```{r}
pCloudy = 0.40
pRain <- 0.10
pCloudyRain <- 0.50

pRainCloudy <- bayesTheorem(pRain, pCloudy, pCloudyRain)
pRainCloudy
```
# Data Cleaning 1

```{r}
url <- 'https://www.stat.berkeley.edu/users/statlabs/data/video.data'
video <- read.table(url)
head(video)
```
```{r}
names(video)
```
```{r}
colnames(video)
```

```{r}
summary(video)
```

```{r}
video <- read.table(url, header = TRUE)
```

```{r}
dim(video)
```
```{r}
head(video)
```
```{r}
tail(video)
```
```{r}
names(video)
```
```{r}
summary(video)
```
# Exploratory Data Analysis
```{r}
# Data structure
str(video)
```
```{r}
# change the attribute level
video$like <- factor(video$like)
levels(video$like)
```
```{r}
levels(video$like) <- c('Never played', 
                        'Very much', 
                        'Somewhat', 
                        'Not really', 
                        'Not at all',
                        'No response')
levels(video$like)
```

```{r}
video$where <- factor(video$where)
levels(video$where)
levels(video$where) <- c('Arcade', 
                         'Console', 
                         'Personal computer', 
                         'Computer and console', 
                         'Arcade and home(console or computer)', 
                         'Arcade and home (both console and computer)',
                         'No response')
levels(video$where)
```
```{r}
str(video)
```
```{r}
head(video)
```

